"""Init migration

Revision ID: 17bb51fcd27c
Revises: 
Create Date: 2021-01-24 15:41:04.141287

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '17bb51fcd27c'
down_revision = None
branch_labels = None
depends_on = None


# noinspection SqlNoDataSourceInspection,SqlResolve
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'artists',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('city', sa.String(length=120), nullable=False),
        sa.Column('state', sa.String(length=120), nullable=False),
        sa.Column('phone', sa.String(length=120), nullable=True),
        sa.Column('image_link', sa.String(length=500), nullable=False),
        sa.Column('facebook_link', sa.String(length=120), nullable=True),
        sa.Column('website', sa.String(length=120), nullable=True),
        sa.Column('seeking_description', sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('facebook_link'),
        sa.UniqueConstraint('phone'),
        sa.UniqueConstraint('website')
    )
    op.create_table(
        'genres',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id')
    )
    op.create_table(
        'venues',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('city', sa.String(length=120), nullable=False),
        sa.Column('state', sa.String(length=120), nullable=False),
        sa.Column('address', sa.String(length=120), nullable=False),
        sa.Column('phone', sa.String(length=120), nullable=True),
        sa.Column('image_link', sa.String(length=500), nullable=False),
        sa.Column('facebook_link', sa.String(length=120), nullable=True),
        sa.Column('website', sa.String(length=120), nullable=True),
        sa.Column('seeking_description', sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('facebook_link'),
        sa.UniqueConstraint('phone'),
        sa.UniqueConstraint('website')
    )
    op.create_table(
        'genres_artists',
        sa.Column('genre_id', sa.Integer(), nullable=False),
        sa.Column('artist_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('genre_id', 'artist_id')
    )
    op.create_table(
        'genres_venues',
        sa.Column('genre_id', sa.Integer(), nullable=False),
        sa.Column('venue_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('genre_id', 'venue_id')
    )
    op.create_table(
        'shows',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('artist_id', sa.Integer(), nullable=True),
        sa.Column('venue_id', sa.Integer(), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # Adding default genres
    genres = [
        'Alternative',
        'Blues',
        'Classical',
        'Country',
        'Electronic',
        'Folk',
        'Funk',
        'Hip-Hop',
        'Heavy Metal',
        'Instrumental',
        'Jazz', 'Jazz',
        'Musical Theatre',
        'Pop',
        'Punk',
        'R&B',
        'Reggae',
        'Rock n Roll',
        'Soul',
        'Other',
    ]
    for g in genres:
        op.execute(f"INSERT INTO genres (name) VALUES ('{g}')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    op.drop_table('genres_venues')
    op.drop_table('genres_artists')
    op.drop_table('venues')
    op.drop_table('genres')
    op.drop_table('artists')
    # ### end Alembic commands ###
